# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BuildLintTestWorkflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: "yarn"
    - name: Add npm token
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Install dependencies
      run: yarn install --frozen-lockfile --check-files
    - name: Build
      run: yarn run build
    - name: Test
      run: yarn run test
    - name: Lint
      run: yarn run lint
