name: Publish to NPM
on:
  workflow_run:
    workflows: [BuildLintTestWorkflow]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: "yarn"
      - name: Add npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Build and copy npmrc
        run: |
          yarn run build
          yarn run copyNpmrc
          yarn run copyReleaseNotes
          yarn run test
          yarn run doc
      - name: Publish
        working-directory: ./dist/resilient-http-client
        run: npm publish
